### ISSUE TITLE
Add more things!

### ISSUE THREAD

**Issue by nicpottier** [nyaruka/gocommon#21]
This is more a urns package than a gocommon package.

There are a bunch of things which we could probably move from courier / goflow / mailroom to here to unify our use. Some ideas:
 * UUID handling / generation
 * fair queueing / task running
 * HTTP request / response logging and tracing
 * DB utilities for batch inserts / updates (in mailroom)

**Comment by rowanseymour** [comment]
I've done some work to break up the goflow utils package into smaller specialized parts, and I think these 3 packages could now move into gocommon:

* https://github.com/nyaruka/goflow/tree/master/utils/dates - `Date` and `TimeOfDay` types, mockable `Now()`, date utils
* https://github.com/nyaruka/goflow/tree/master/utils/random - mockable rand functions
* https://github.com/nyaruka/goflow/tree/master/utils/uuids - `UUID` type, validation and mockable generation

**Comment by rowanseymour** [comment]
Re-upping this given that we could move the `httpx` package from goflow here to make it easier to use rp-archiver to use the same HTTP retry code there
