### ISSUE TITLE
+ is a valid phone numbers character

### ISSUE THREAD

**Issue by norkans7** [nyaruka/gocommon#3]
This issue is causing to trim + on number(https://github.com/nyaruka/gocommon/blob/master/urns/urns.go#L289) and return the number missing the + when phonenumbers lib does not consider the number to be valid https://github.com/nyaruka/gocommon/blob/master/urns/urns.go#L305

https://github.com/nyaruka/gocommon/blob/master/urns/urns.go#L70

**Comment by nicpottier** [comment]
We add the plus immediately below. The logic here looks the same as RapidPro:
  https://github.com/nyaruka/rapidpro/blob/master/temba/contacts/models.py#L240

So I think the problem is likely not here, perhaps in phonenumbers?

**Comment by nicpottier** [comment]
That number passes in gophonenumbers parsing..

**Comment by norkans7** [comment]
what do you mean?

**Comment by nicpottier** [comment]
It was passing the parsing but not the validity check. I updated the phonenumbers db in:
  https://github.com/nyaruka/phonenumbers/commit/9c5a28db50f85d24a31e1e9cebb6bff9f6671913

And it passes now. So we just need to update the vendored version.
